env: standard

runtime: nodejs16

entrypoint: npm run start:prod

instance_class: B1

automatic_scaling:
  min_instances: 0
  max_instances: 2
  min_idle_instances: automatic
  max_idle_instances: 1
  max_concurrent_requests: 80
  min_pending_latency: 3000ms
  max_pending_latency: automatic
