name: Deploy to Google AppEngine

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Google AppEngine

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build Nest.js application
        run: |
          npm i
          npm run build

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy App to GAE
        run: gcloud app deploy --quiet
